In [118]:
import pandas as pd
import numpy as np

In [119]:
moviesData = pd.read_csv("tmdb_5000_movies.csv")
creditsData = pd.read_csv("tmdb_5000_credits.csv")
# moviesData.head()
creditsData.head()
# moviesData['genres'].head()
# moviesData.shape

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [120]:
moviesData = moviesData.merge(creditsData, on="title")

In [121]:
moviesData.shape
moviesData.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [122]:
moviesData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [123]:
moviesData = moviesData[['genres','id','cast', 'crew','overview','title', 'keywords']]

In [124]:
moviesData.head()
moviesData.shape

(4809, 7)

In [125]:
moviesData.isnull().sum()

genres      0
id          0
cast        0
crew        0
overview    3
title       0
keywords    0
dtype: int64

In [126]:
moviesData.dropna(inplace=True)

In [127]:
moviesData.isnull().sum()

genres      0
id          0
cast        0
crew        0
overview    0
title       0
keywords    0
dtype: int64

In [128]:
moviesData.duplicated().sum()

0

In [129]:
moviesData['genres'].head()

0    [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1    [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2    [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3    [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4    [{"id": 28, "name": "Action"}, {"id": 12, "nam...
Name: genres, dtype: object

In [130]:
import ast
# splits the source code into tokens based on the grammar

In [131]:
def helper(obj): # Create a function definition
    Lst = [] # Create an empty list
    for i in ast.literal_eval(obj): # literal_eval used to convert a string of dictionary/json into a dictionary/json
        Lst.append(i['name']) # append the genres names into the list and return the list at the end
    return Lst

In [132]:
moviesData['genres'] = moviesData['genres'].apply(helper)

In [133]:
moviesData['keywords'] = moviesData['keywords'].apply(helper)

In [134]:
moviesData

,genres,id,cast,crew,overview,title,keywords
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","In the 22nd century, a paraplegic Marine is di...",Avatar,"[culture clash, future, space war, space colon..."
1,"[Adventure, Fantasy, Action]",285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ..."
2,"[Action, Adventure, Crime]",206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",A cryptic message from Bondâ€™s past sends him o...,Spectre,"[spy, based on novel, secret agent, sequel, mi..."
3,"[Action, Crime, Drama, Thriller]",49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",Following the death of District Attorney Harve...,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i..."
4,"[Action, Adventure, Science Fiction]",49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","John Carter is a war-weary, former military ca...",John Carter,"[based on novel, mars, medallion, space travel..."
...,...,...,...,...,...,...,...
4804,"[Action, Crime, Thriller]",9367,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de...",El Mariachi just wants to play his guitar and ...,El Mariachi,"[united statesâ€“mexico barrier, legs, arms, pap..."
4805,"[Comedy, Romance]",72766,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de...",A newlywed couple's honeymoon is upended by th...,Newlyweds,[]
4806,"[Comedy, Drama, Romance, TV Movie]",231617,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de...","""Signed, Sealed, Delivered"" introduces a dedic...","Signed, Sealed, Delivered","[date, love at first sight, narration, investi..."
4807,[],126186,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de...",When ambitious New York attorney Sam is sent t...,Shanghai Calling,[]
4808,[Documentary],25975,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de...",Ever since the second grade when he first saw ...,My Date with Drew,"[obsession, camcorder, crush, dream girl]"

In [135]:
def helperCast(obj): # Create a function definition
    Lst = [] # Create an empty list
    counter = 0
    for i in ast.literal_eval(obj): # literal_eval used to convert a string of dictionary/json into a dictionary/json
        if(counter!=5):
            Lst.append(i['name']) # append the genres names into the list and return the list at the end
            counter=counter+1
        else:
            break
            
    return Lst

In [136]:
moviesData['cast'] = moviesData['cast'].apply(helperCast)

In [137]:
moviesData.head()

,genres,id,cast,crew,overview,title,keywords
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","In the 22nd century, a paraplegic Marine is di...",Avatar,"[culture clash, future, space war, space colon..."
1,"[Adventure, Fantasy, Action]",285,"[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ..."
2,"[Action, Adventure, Crime]",206647,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",A cryptic message from Bondâ€™s past sends him o...,Spectre,"[spy, based on novel, secret agent, sequel, mi..."
3,"[Action, Crime, Drama, Thriller]",49026,"[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",Following the death of District Attorney Harve...,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i..."
4,"[Action, Adventure, Science Fiction]",49529,"[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","John Carter is a war-weary, former military ca...",John Carter,"[based on novel, mars, medallion, space travel..."

In [138]:
def helperCrew(obj): # Create a function definition
    Lst = [] # Create an empty list
    for i in ast.literal_eval(obj): # literal_eval used to convert a string of dictionary/json into a dictionary/json
        if(i['job'] == "Director"):
            Lst.append(i['name']) # append the genres names into the list and return the list at the end
            break
    return Lst

In [139]:
moviesData['crew'] = moviesData['crew'].apply(helperCrew)

In [140]:
moviesData

,genres,id,cast,crew,overview,title,keywords
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron],"In the 22nd century, a paraplegic Marine is di...",Avatar,"[culture clash, future, space war, space colon..."
1,"[Adventure, Fantasy, Action]",285,"[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski],"Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ..."
2,"[Action, Adventure, Crime]",206647,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...",[Sam Mendes],A cryptic message from Bondâ€™s past sends him o...,Spectre,"[spy, based on novel, secret agent, sequel, mi..."
3,"[Action, Crime, Drama, Thriller]",49026,"[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan],Following the death of District Attorney Harve...,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i..."
4,"[Action, Adventure, Science Fiction]",49529,"[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton],"John Carter is a war-weary, former military ca...",John Carter,"[based on novel, mars, medallion, space travel..."
...,...,...,...,...,...,...,...
4804,"[Action, Crime, Thriller]",9367,"[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...",[Robert Rodriguez],El Mariachi just wants to play his guitar and ...,El Mariachi,"[united statesâ€“mexico barrier, legs, arms, pap..."
4805,"[Comedy, Romance]",72766,"[Edward Burns, Kerry BishÃ©, Marsha Dietlein, C...",[Edward Burns],A newlywed couple's honeymoon is upended by th...,Newlyweds,[]
4806,"[Comedy, Drama, Romance, TV Movie]",231617,"[Eric Mabius, Kristin Booth, Crystal Lowe, Geo...",[Scott Smith],"""Signed, Sealed, Delivered"" introduces a dedic...","Signed, Sealed, Delivered","[date, love at first sight, narration, investi..."
4807,[],126186,"[Daniel Henney, Eliza Coupe, Bill Paxton, Alan...",[Daniel Hsia],When ambitious New York attorney Sam is sent t...,Shanghai Calling,[]
4808,[Documentary],25975,"[Drew Barrymore, Brian Herzlinger, Corey Feldm...",[Brian Herzlinger],Ever since the second grade when he first saw ...,My Date with Drew,"[obsession, camcorder, crush, dream girl]"

In [141]:
moviesData.isnull().sum()

genres      0
id          0
cast        0
crew        0
overview    0
title       0
keywords    0
dtype: int64

In [142]:
moviesData

,genres,id,cast,crew,overview,title,keywords
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron],"In the 22nd century, a paraplegic Marine is di...",Avatar,"[culture clash, future, space war, space colon..."
1,"[Adventure, Fantasy, Action]",285,"[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski],"Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ..."
2,"[Action, Adventure, Crime]",206647,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...",[Sam Mendes],A cryptic message from Bondâ€™s past sends him o...,Spectre,"[spy, based on novel, secret agent, sequel, mi..."
3,"[Action, Crime, Drama, Thriller]",49026,"[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan],Following the death of District Attorney Harve...,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i..."
4,"[Action, Adventure, Science Fiction]",49529,"[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton],"John Carter is a war-weary, former military ca...",John Carter,"[based on novel, mars, medallion, space travel..."
...,...,...,...,...,...,...,...
4804,"[Action, Crime, Thriller]",9367,"[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...",[Robert Rodriguez],El Mariachi just wants to play his guitar and ...,El Mariachi,"[united statesâ€“mexico barrier, legs, arms, pap..."
4805,"[Comedy, Romance]",72766,"[Edward Burns, Kerry BishÃ©, Marsha Dietlein, C...",[Edward Burns],A newlywed couple's honeymoon is upended by th...,Newlyweds,[]
4806,"[Comedy, Drama, Romance, TV Movie]",231617,"[Eric Mabius, Kristin Booth, Crystal Lowe, Geo...",[Scott Smith],"""Signed, Sealed, Delivered"" introduces a dedic...","Signed, Sealed, Delivered","[date, love at first sight, narration, investi..."
4807,[],126186,"[Daniel Henney, Eliza Coupe, Bill Paxton, Alan...",[Daniel Hsia],When ambitious New York attorney Sam is sent t...,Shanghai Calling,[]
4808,[Documentary],25975,"[Drew Barrymore, Brian Herzlinger, Corey Feldm...",[Brian Herzlinger],Ever since the second grade when he first saw ...,My Date with Drew,"[obsession, camcorder, crush, dream girl]"

In [143]:
moviesData['overview'] = moviesData['overview'].apply(lambda x:x.split())

In [144]:
moviesData.head()

,genres,id,cast,crew,overview,title,keywords
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron],"[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,"[culture clash, future, space war, space colon..."
1,"[Adventure, Fantasy, Action]",285,"[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski],"[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ..."
2,"[Action, Adventure, Crime]",206647,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...",[Sam Mendes],"[A, cryptic, message, from, Bondâ€™s, past, send...",Spectre,"[spy, based on novel, secret agent, sequel, mi..."
3,"[Action, Crime, Drama, Thriller]",49026,"[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan],"[Following, the, death, of, District, Attorney...",The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i..."
4,"[Action, Adventure, Science Fiction]",49529,"[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton],"[John, Carter, is, a, war-weary,, former, mili...",John Carter,"[based on novel, mars, medallion, space travel..."

In [145]:
# We would like to combine the words with spaces together like 'Sam Worthingthon' as 'SamWorthingthon', 'Sam Mendes' as 'SamMendes' 
# so as to avoid confusion for our recommendation system so that it does not recommend Sam Worthingthon's movies for 
# Sam Mendes movies and so on. Same is applied on cast, crew, keywords, genres.'Science Fiction' as 'ScienceFiction' 

moviesData['genres'] = moviesData['genres'].apply(lambda x: [i.replace(" ", "") for i in x])
moviesData['crew'] = moviesData['crew'].apply(lambda x: [i.replace(" ", "") for i in x])
moviesData['cast'] = moviesData['cast'].apply(lambda x: [i.replace(" ", "") for i in x])
moviesData['keywords'] = moviesData['keywords'].apply(lambda x: [i.replace(" ", "") for i in x])
moviesData.head()

,genres,id,cast,crew,overview,title,keywords
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,"[cultureclash, future, spacewar, spacecolony, ..."
1,"[Adventure, Fantasy, Action]",285,"[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,"[ocean, drugabuse, exoticisland, eastindiatrad..."
2,"[Action, Adventure, Crime]",206647,"[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send...",Spectre,"[spy, basedonnovel, secretagent, sequel, mi6, ..."
3,"[Action, Crime, Drama, Thriller]",49026,"[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan],"[Following, the, death, of, District, Attorney...",The Dark Knight Rises,"[dccomics, crimefighter, terrorist, secretiden..."
4,"[Action, Adventure, ScienceFiction]",49529,"[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili...",John Carter,"[basedonnovel, mars, medallion, spacetravel, p..."

In [146]:
moviesData['tags'] = moviesData['overview'] + moviesData['genres'] + moviesData['keywords'] + moviesData['cast'] + moviesData['crew']

In [147]:
moviesDf = moviesData[['id','title','tags']]

In [148]:
moviesDf['tags'] = moviesDf['tags'].apply(lambda x:" ".join(x))
moviesDf['tags'] = moviesDf['tags'].apply(lambda x:(x.lower()))

C:\Users\shivansh arora\AppData\Local\Temp\ipykernel_32856\2616957361.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  moviesDf['tags'] = moviesDf['tags'].apply(lambda x:" ".join(x))
C:\Users\shivansh arora\AppData\Local\Temp\ipykernel_32856\2616957361.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  moviesDf['tags'] = moviesDf['tags'].apply(lambda x:(x.lower()))

In [149]:
moviesDf

,id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,a newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,when ambitious new york attorney sam is sent t...
4808,25975,My Date with Drew,ever since the second grade when he first saw ...

In [150]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 3000, stop_words = 'english')
vector = cv.fit_transform(moviesDf['tags']).toarray()
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [151]:
import nltk

In [152]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

def fn(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
        
    return " ".join(y)

In [153]:
moviesDf['tags'].apply(fn)

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bondâ€™ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...
4804    el mariachi just want to play hi guitar and ca...
4805    a newlyw couple' honeymoon is upend by the arr...
4806    "signed, sealed, delivered" introduc a dedic q...
4807    when ambiti new york attorney sam is sent to s...
4808    ever sinc the second grade when he first saw h...
Name: tags, Length: 4806, dtype: object

In [154]:
# res = cv.get_feature_names_out()
# res
# vector[0]

In [155]:
# as number of data increases, the euclidean distance calculation method fails and cosine method is more preffered to find the similarity
# between two vectors
from sklearn.metrics.pairwise import cosine_similarity

In [156]:
similarity = cosine_similarity(vector)
similarity

array([[1.        , 0.09869275, 0.06356417, ..., 0.02787473, 0.03030303,
        0.        ],
       [0.09869275, 1.        , 0.06900656, ..., 0.03026138, 0.        ,
        0.        ],
       [0.06356417, 0.06900656, 1.        , ..., 0.02923527, 0.        ,
        0.        ],
       ...,
       [0.02787473, 0.03026138, 0.02923527, ..., 1.        , 0.0836242 ,
        0.0594701 ],
       [0.03030303, 0.        , 0.        , ..., 0.0836242 , 1.        ,
        0.06465082],
       [0.        , 0.        , 0.        , ..., 0.0594701 , 0.06465082,
        1.        ]])

In [157]:
moviesDf[moviesDf['title'] == 'Gandhi'].index[0]

2030

In [158]:
def recommend(movie):
    index = moviesDf[moviesDf['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(moviesDf.iloc[i[0]].title)

In [168]:
recommend('Thor: The Dark World')

Thor
Ant-Man
Avengers: Age of Ultron
Iron Man 3
The Avengers

In [160]:
import pickle

In [161]:
pickle.dump(moviesDf.to_dict(), open('moviesDf_Dict.pkl', 'wb'))

In [162]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))

In [163]:
moviesDf

,id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,a newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,when ambitious new york attorney sam is sent t...
4808,25975,My Date with Drew,ever since the second grade when he first saw ...